# Generated by Django 4.2.16 on 2026-07-02 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('nl_prompt', models.TextField()),
                ('target_columns', models.CharField(max_length=500)),
                ('replacement_value', models.CharField(max_length=500)),
                ('generated_regex', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('result_path', models.CharField(blank=True, max_length=500)),
                ('result_row_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
